export const filters = {
  include_adult: "include_adult",
  include_video: "include_video",
  language: "language",
  page: "page",
  "primary_release_date.gte": "primary_release_date.gte",
  "primary_release_date.lte": "primary_release_date.lte",
  sort_by: "sort_by",
  "vote_average.gte": "vote_average.gte",
  "vote_average.lte": "vote_average.lte",
  "vote_count.gte": "vote_count.gte",
  "vote_count.lte": "vote_count.lte",
  watch_region: "watch_region",
  with_genres: "with_genres",
  with_origin_country: "with_origin_country",
  with_people: "with_people",
  "with_runtime.gte": "with_runtime.gte",
  "with_runtime.lte": "with_runtime.lte",
  with_watch_providers: "with_watch_providers",
  without_genres: "without_genres",
};

export const defaultFilters = {
  include_adult: false,
  include_video: false,
  language: "fr-FR",
  page: 1,
  "primary_release_date.gte": null,
  "primary_release_date.lte": null,
  sort_by: "popularity.desc",
  "vote_average.gte": null,
  "vote_average.lte": null,
  "vote_count.gte": null,
  "vote_count.lte": null,
  watch_region: null,
  with_genres: null,
  with_origin_country: null,
  with_people: null,
  "with_runtime.gte": null,
  "with_runtime.lte": null,
  with_watch_providers: null,
  without_genres: null,
};
